config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path("", include("djsniper.sniper.urls", namespace="sniper")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("djsniper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djsniper/sniper/urls.py
from django.urls import path
from . import views

app_name = "sniper"

urlpatterns = [
    path("", views.ProjectListView.as_view(), name="project-list"),
    path("create/", views.ProjectCreateView.as_view(), name="project-create"),
    path("project/<pk>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path(
        "project/<pk>/update/", views.ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "project/<pk>/delete/", views.ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/<pk>/clear/", views.ProjectClearView.as_view(), name="project-clear"),
    path("project/<pk>/fetch-nfts/", views.FetchNFTsView.as_view(), name="fetch-nfts"),
]

djsniper/users/urls.py
from django.urls import path

from djsniper.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

djsniper/sniper/models.py
from django.db import models


class NFTProject(models.Model):
    contract_address = models.CharField(max_length=100)
    contract_abi = models.TextField()
    name = models.CharField(max_length=50)  # e.g BAYC
    number_of_nfts = models.PositiveIntegerField()

    def __str__(self) -> str:
        return self.name


class NFT(models.Model):
    project = models.ForeignKey(
        NFTProject, on_delete=models.CASCADE, related_name="nfts"
    )
    rarity_score = models.FloatField(null=True)
    nft_id = models.PositiveIntegerField()
    image_url = models.CharField(max_length=200)
    rank = models.PositiveIntegerField(null=True)

    def __str__(self):
        return f"{self.project.name}: {self.nft_id}"


class NFTAttribute(models.Model):
    project = models.ForeignKey(
        NFTProject, on_delete=models.CASCADE, related_name="attributes"
    )
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}: {self.value}"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['project', 'name', 'value'], name='unique appversion')
        ]


class NFTTrait(models.Model):
    nft = models.ForeignKey(
        NFT, on_delete=models.CASCADE, related_name="nft_attributes"
    )
    attribute = models.ForeignKey(
        NFTAttribute, on_delete=models.CASCADE, related_name="traits"
    )
    rarity_score = models.FloatField(null=True)

    def __str__(self) -> str:
        return f"{self.attribute.name}: {self.attribute.value}"

djsniper/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for djsniper."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

djsniper/sniper/forms.py
from django import forms
from .models import NFTProject


class ProjectForm(forms.ModelForm):
    class Meta:
        model = NFTProject
        fields = ("name", "contract_address", "contract_abi", "number_of_nfts")


class ConfirmForm(forms.Form):
    hidden = forms.HiddenInput()

djsniper/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

djsniper/sniper/views.py
import json

from celery.result import AsyncResult

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.detail import SingleObjectMixin
from djsniper.sniper.forms import ConfirmForm, ProjectForm
from djsniper.sniper.models import NFTAttribute, NFTProject
from djsniper.sniper.tasks import fetch_and_rank_nfts_task


class ProjectListView(generic.ListView):
    template_name = "sniper/project_list.html"

    def get_queryset(self):
        return NFTProject.objects.all()


class ProjectDetailView(generic.DetailView):
    template_name = "sniper/project_detail.html"

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nft_project = self.get_object()
        order = self.request.GET.get("order", None)
        nfts = nft_project.nfts.all()
        if order == "rank":
            nfts = nfts.order_by("rank")
        context.update({"nfts": nfts[0:12]})
        return context


class ProjectCreateView(generic.CreateView):
    template_name = "sniper/project_create.html"
    form_class = ProjectForm

    def form_valid(self, form):
        instance = form.save()
        return redirect("sniper:project-detail", pk=instance.id)

    def get_queryset(self):
        return NFTProject.objects.all()


class ProjectUpdateView(generic.UpdateView):
    template_name = "sniper/project_update.html"
    form_class = ProjectForm

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-detail", kwargs={"pk": self.get_object().id})


class ProjectDeleteView(generic.DeleteView):
    template_name = "sniper/project_delete.html"

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-list")


class ProjectClearView(SingleObjectMixin, generic.FormView):
    template_name = "sniper/project_clear.html"
    form_class = ConfirmForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_queryset(self):
        return NFTProject.objects.all()

    def form_valid(self, form):
        nft_project = self.get_object()
        nft_project.nfts.all().delete()
        NFTAttribute.objects.filter(project=nft_project).delete()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("sniper:project-detail", kwargs={"pk": self.kwargs["pk"]})


def nft_list(request):
    project = NFTProject.objects.get(name="BAYC")
    nfts = project.nfts.all().order_by("-rarity_score")[0:12]
    return render(request, "nfts.html", {"nfts": nfts})


class FetchNFTsView(generic.FormView):
    template_name = "sniper/fetch_nfts.html"
    form_class = ConfirmForm

    def form_valid(self, form):
        result = fetch_and_rank_nfts_task.apply_async((self.kwargs["pk"],), countdown=1)
        return render(self.request, self.template_name, {"task_id": result.task_id})


def get_progress(request, task_id):
    result = AsyncResult(task_id)
    response_data = {
        "state": result.state,
        "details": result.info,
    }
    return HttpResponse(json.dumps(response_data), content_type="application/json")

djsniper/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

djsniper/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

djsniper/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Dj NFT Sniper{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Django Self-Hosted NFT Rarity Sniper">
  <meta name="author" content="admin">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

  {% block css %}
  <!-- Your stuff: Third-party CSS libraries go here -->
  <!-- This file stores project-specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
    ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <!-- place project specific Javascript in this file -->
  <script defer src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}

</head>

<body class="h-full">

  <div class="min-h-full">
    <nav class="bg-white border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex">
            <div class="hidden sm:-my-px sm:flex sm:space-x-8">
              <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
              <a href="{% url 'sniper:project-list' %}"
                class="border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
                aria-current="page">
                Projects
              </a>

              <a href="{% url 'sniper:project-create' %}"
                class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                Add Project
              </a>

            </div>
          </div>
          <div class="hidden sm:ml-6 sm:flex sm:items-center">
            <!-- Profile dropdown -->
            <div class="ml-3 relative">

            </div>
          </div>

        </div>
      </div>
    </nav>

    <div class="py-10">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}
      <main>
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
          {% block content %}
          <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
        </div>
      </main>
    </div>
  </div>

  {% block modal %}{% endblock modal %}

  {% block inline_javascript %}
  {% comment %}
  Script tags with only code, no src (defer by default). To run
  with a "defer" so that you run run inline code:
  <script>
    window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */ });
  </script>
  {% endcomment %}
  {% endblock inline_javascript %}
</body>

</html>

djsniper/templates/nfts.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-3xl font-bold leading-tight text-gray-900">
    Bored Ape Yacht Club
</h1>
<div class="mt-5 grid grid-cols-4 gap-4">
    {% for nft in nfts %}
    <div class="py-3 px-3 border border-gray-200 shadow-sm">
        <img class="w-full rounded-md" src="https://ipfs.io/ipfs/{{ nft.image_url }}" />
        <div class="mt-1">
            <h1 class="text-lg text-gray-800 font-bold">#{{ nft.nft_id }}</h1>
            <p class="text-base text-gray-600">Score: {{ nft.rarity_score|floatformat:2 }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}