config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path("", include("djsniper.sniper.urls", namespace="sniper")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("djsniper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djsniper/sniper/urls.py
from django.urls import path
from . import views

app_name = "sniper"

urlpatterns = [
    path("", views.ProjectListView.as_view(), name="project-list"),
    path("create/", views.ProjectCreateView.as_view(), name="project-create"),
    path("project/<pk>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path(
        "project/<pk>/update/", views.ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "project/<pk>/delete/", views.ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/<pk>/clear/", views.ProjectClearView.as_view(), name="project-clear"),
    path("project/<pk>/fetch-nfts/", views.FetchNFTsView.as_view(), name="fetch-nfts"),
]

djsniper/users/urls.py
from django.urls import path

from djsniper.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

djsniper/sniper/models.py
from django.db import models


class NFTProject(models.Model):
    contract_address = models.CharField(max_length=100)
    contract_abi = models.TextField()
    name = models.CharField(max_length=50)  # e.g BAYC
    number_of_nfts = models.PositiveIntegerField()

    def __str__(self) -> str:
        return self.name


class NFT(models.Model):
    project = models.ForeignKey(
        NFTProject, on_delete=models.CASCADE, related_name="nfts"
    )
    rarity_score = models.FloatField(null=True)
    nft_id = models.PositiveIntegerField()
    image_url = models.CharField(max_length=200)
    rank = models.PositiveIntegerField(null=True)

    def __str__(self):
        return f"{self.project.name}: {self.nft_id}"


class NFTAttribute(models.Model):
    project = models.ForeignKey(
        NFTProject, on_delete=models.CASCADE, related_name="attributes"
    )
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}: {self.value}"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['project', 'name', 'value'], name='unique appversion')
        ]


class NFTTrait(models.Model):
    nft = models.ForeignKey(
        NFT, on_delete=models.CASCADE, related_name="nft_attributes"
    )
    attribute = models.ForeignKey(
        NFTAttribute, on_delete=models.CASCADE, related_name="traits"
    )
    rarity_score = models.FloatField(null=True)

    def __str__(self) -> str:
        return f"{self.attribute.name}: {self.attribute.value}"

djsniper/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for djsniper."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

djsniper/sniper/forms.py
from django import forms
from .models import NFTProject


class ProjectForm(forms.ModelForm):
    class Meta:
        model = NFTProject
        fields = ("name", "contract_address", "contract_abi", "number_of_nfts")


class ConfirmForm(forms.Form):
    hidden = forms.HiddenInput()

djsniper/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

djsniper/sniper/views.py
import json

from celery.result import AsyncResult

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.detail import SingleObjectMixin
from djsniper.sniper.forms import ConfirmForm, ProjectForm
from djsniper.sniper.models import NFTAttribute, NFTProject
from djsniper.sniper.tasks import fetch_and_rank_nfts_task


class ProjectListView(generic.ListView):
    template_name = "sniper/project_list.html"

    def get_queryset(self):
        return NFTProject.objects.all()


class ProjectDetailView(generic.DetailView):
    template_name = "sniper/project_detail.html"

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nft_project = self.get_object()
        order = self.request.GET.get("order", None)
        nfts = nft_project.nfts.all()
        if order == "rank":
            nfts = nfts.order_by("rank")
        context.update({"nfts": nfts[0:12]})
        return context


class ProjectCreateView(generic.CreateView):
    template_name = "sniper/project_create.html"
    form_class = ProjectForm

    def form_valid(self, form):
        instance = form.save()
        return redirect("sniper:project-detail", pk=instance.id)

    def get_queryset(self):
        return NFTProject.objects.all()


class ProjectUpdateView(generic.UpdateView):
    template_name = "sniper/project_update.html"
    form_class = ProjectForm

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-detail", kwargs={"pk": self.get_object().id})


class ProjectDeleteView(generic.DeleteView):
    template_name = "sniper/project_delete.html"

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-list")


class ProjectClearView(SingleObjectMixin, generic.FormView):
    template_name = "sniper/project_clear.html"
    form_class = ConfirmForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_queryset(self):
        return NFTProject.objects.all()

    def form_valid(self, form):
        nft_project = self.get_object()
        nft_project.nfts.all().delete()
        NFTAttribute.objects.filter(project=nft_project).delete()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("sniper:project-detail", kwargs={"pk": self.kwargs["pk"]})


def nft_list(request):
    project = NFTProject.objects.get(name="BAYC")
    nfts = project.nfts.all().order_by("-rarity_score")[0:12]
    return render(request, "nfts.html", {"nfts": nfts})


class FetchNFTsView(generic.FormView):
    template_name = "sniper/fetch_nfts.html"
    form_class = ConfirmForm

    def form_valid(self, form):
        result = fetch_and_rank_nfts_task.apply_async((self.kwargs["pk"],), countdown=1)
        return render(self.request, self.template_name, {"task_id": result.task_id})


def get_progress(request, task_id):
    result = AsyncResult(task_id)
    response_data = {
        "state": result.state,
        "details": result.info,
    }
    return HttpResponse(json.dumps(response_data), content_type="application/json")

djsniper/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

djsniper/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

djsniper/templates/sniper/fetch_nfts.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="max-w-xl mx-auto">
    <h2 class="text-xl leading-6 font-medium text-gray-900">Fetch NFTs</h2>
    <p class="text-gray-600">Confirming this form will start the celery tasks</p>
    <div class="flex flex-col">
        {% if task_id %}

        <div class='progress-wrapper'>
            <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">
                &nbsp;
            </div>
        </div>
        <div id="progress-bar-message">Waiting for progress to start...</div>

        {% else %}

        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit"
                class="mt-5 rounded shadow-md px-3 py-1 text-lg text-white bg-blue-500 hover:bg-blue-600">
                Start
            </button>
        </form>

        {% endif %}
    </div>
</div>

{% endblock content %}

{% block inline_javascript %}
<script src="{% static 'js/celery_progress.js' %}"></script>
<script>
    const taskID = "{{ task_id }}"
    if (taskID) {
        var progressUrl = `/celery-progress/${taskID}/`;
        CeleryProgressBar.initProgressBar(progressUrl);
    }
</script>

{% endblock inline_javascript %}

djsniper/templates/sniper/project_clear.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <div class="border-b border-gray-200 py-5">
        <h1 class="text-3xl font-bold leading-tight text-gray-900">
            Clear Project Data
        </h1>
    </div>

    <div class="mt-3">
        <a href="{% url 'sniper:project-detail' object.id %}" class="text-blue-500 hover:text-blue-600">
            Go back to {{ object.name }}
        </a>
    </div>

    <form class="mt-3" method="post">
        {% csrf_token %}
        <button
            class="bg-red-200 text-red-600 hover:bg-red-200 hover:text-red-800 shadow rounded px-3 py-2">Submit</button>
    </form>

</div>

{% endblock content %}

djsniper/templates/sniper/project_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
        Create Project
    </h1>

    <form class="mt-3" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button
            class="bg-gray-200 text-gray-600 hover:bg-gray-200 hover:text-gray-800 shadow rounded px-3 py-2">Submit</button>
    </form>
</div>

{% endblock content %}

djsniper/templates/sniper/project_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <div class="border-b border-gray-200 py-5">
        <h1 class="text-3xl font-bold leading-tight text-gray-900">
            Delete Project
        </h1>
    </div>

    <div class="mt-3">
        <a href="{% url 'sniper:project-detail' object.id %}" class="text-blue-500 hover:text-blue-600">
            Go back to {{ object.name }}
        </a>
    </div>

    <form class="mt-3" method="post">
        {% csrf_token %}
        <button
            class="bg-red-200 text-red-600 hover:bg-red-200 hover:text-red-800 shadow rounded px-3 py-2">Submit</button>
    </form>

</div>

{% endblock content %}

djsniper/templates/sniper/project_detail.html
{% extends "base.html" %}

{% block content %}

<div class="max-w-xl mx-auto">
    <div class="flex items-center justify-between border-b border-gray-200 py-5">
        <div>
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
                {{ object.name }}
            </h1>
        </div>
        <div>
            <a href="?order=rank"
                class="bg-blue-200 text-blue-600 hover:bg-blue-200 hover:text-blue-800 shadow rounded px-3 py-2">
                Order
            </a>
        </div>
    </div>

    <div class="mt-5">
        <p>{{ object.number_of_nfts }} NFTs</p>
        <div class="mt-5 grid grid-cols-4 gap-4">
            {% for nft in nfts %}
            <div class="py-3 px-3 border border-gray-200 shadow-sm">
                <img class="w-full rounded-md" src="https://ipfs.io/ipfs/{{ nft.image_url }}" />
                <div class="mt-1">
                    <h1 class="text-lg text-gray-800 font-bold">#{{ nft.nft_id }}</h1>
                    <p class="text-base text-gray-600">Score: {{ nft.rarity_score|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="py-10">
            <a href="{% url 'sniper:fetch-nfts' object.id %}"
                class="bg-green-200 text-green-600 hover:bg-green-200 hover:text-green-800 shadow rounded px-3 py-2">
                Fetch NFTs
            </a>
        </div>
    </div>

    <div class="mt-5">
        <a href="{% url 'sniper:project-clear' object.id %}"
            class="bg-gray-200 text-gray-600 hover:bg-gray-200 hover:text-gray-800 shadow rounded px-3 py-2">
            Clear NFT data
        </a>
        <a href="{% url 'sniper:project-update' object.id %}"
            class="ml-3 bg-blue-200 text-blue-600 hover:bg-blue-200 hover:text-blue-800 shadow rounded px-3 py-2">
            Update
        </a>
        <a href="{% url 'sniper:project-delete' object.id %}"
            class="ml-3 bg-red-200 text-red-600 hover:bg-red-200 hover:text-red-800 shadow rounded px-3 py-2">
            Delete
        </a>
    </div>
</div>

{% endblock content %}

djsniper/templates/sniper/project_list.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-3xl font-bold leading-tight text-gray-900">
    Projects
</h1>

{% for project in object_list %}

<div class="mt-3 py-3 px-3 border border-gray-200 shadow-md rounded">
    <a href="{% url 'sniper:project-detail' project.id %}">
        <p class="text-xl font-bold leading-8"></p>
        {{ project.name }}
        </p>
    </a>
</div>

{% endfor %}

{% endblock content %}

djsniper/templates/sniper/project_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
        Update {{ object.name }}
    </h1>

    <div class="mt-3">
        <a href="{% url 'sniper:project-detail' object.id %}" class="text-blue-500 hover:text-blue-600">
            Go back to {{ object.name }}
        </a>
    </div>

    <form class="mt-3" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button
            class="bg-gray-200 text-gray-600 hover:bg-gray-200 hover:text-gray-800 shadow rounded px-3 py-2">Submit</button>
    </form>
</div>

{% endblock content %}